// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package process

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSocketTrack returns the embedded CollectionSpec for socketTrack.
func loadSocketTrack() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SocketTrackBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load socketTrack: %w", err)
	}

	return spec, err
}

// loadSocketTrackObjects loads socketTrack and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*socketTrackObjects
//	*socketTrackPrograms
//	*socketTrackMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSocketTrackObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSocketTrack()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// socketTrackSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTrackSpecs struct {
	socketTrackProgramSpecs
	socketTrackMapSpecs
	socketTrackVariableSpecs
}

// socketTrackProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTrackProgramSpecs struct {
	KprobeTcpV4Connect     *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v4_connect"`
	KprobeTcpV6Connect     *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v6_connect"`
	KretprobeInetCskAccept *ebpf.ProgramSpec `ebpf:"kretprobe_inet_csk_accept"`
	KretprobeTcpV4Connect  *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_v4_connect"`
	KretprobeTcpV6Connect  *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_v6_connect"`
}

// socketTrackMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTrackMapSpecs struct {
	ActiveSocks *ebpf.MapSpec `ebpf:"active_socks"`
	Events      *ebpf.MapSpec `ebpf:"events"`
}

// socketTrackVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTrackVariableSpecs struct {
}

// socketTrackObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSocketTrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTrackObjects struct {
	socketTrackPrograms
	socketTrackMaps
	socketTrackVariables
}

func (o *socketTrackObjects) Close() error {
	return _SocketTrackClose(
		&o.socketTrackPrograms,
		&o.socketTrackMaps,
	)
}

// socketTrackMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSocketTrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTrackMaps struct {
	ActiveSocks *ebpf.Map `ebpf:"active_socks"`
	Events      *ebpf.Map `ebpf:"events"`
}

func (m *socketTrackMaps) Close() error {
	return _SocketTrackClose(
		m.ActiveSocks,
		m.Events,
	)
}

// socketTrackVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSocketTrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTrackVariables struct {
}

// socketTrackPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSocketTrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTrackPrograms struct {
	KprobeTcpV4Connect     *ebpf.Program `ebpf:"kprobe_tcp_v4_connect"`
	KprobeTcpV6Connect     *ebpf.Program `ebpf:"kprobe_tcp_v6_connect"`
	KretprobeInetCskAccept *ebpf.Program `ebpf:"kretprobe_inet_csk_accept"`
	KretprobeTcpV4Connect  *ebpf.Program `ebpf:"kretprobe_tcp_v4_connect"`
	KretprobeTcpV6Connect  *ebpf.Program `ebpf:"kretprobe_tcp_v6_connect"`
}

func (p *socketTrackPrograms) Close() error {
	return _SocketTrackClose(
		p.KprobeTcpV4Connect,
		p.KprobeTcpV6Connect,
		p.KretprobeInetCskAccept,
		p.KretprobeTcpV4Connect,
		p.KretprobeTcpV6Connect,
	)
}

func _SocketTrackClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockettrack_x86_bpfel.o
var _SocketTrackBytes []byte
